apiVersion: operator.aquasec.com/v1alpha1
kind: AquaEnforcer
metadata:
  name: aqua
spec:
  infra:
    serviceAccount: "aqua-sa"
    version: "4.6"
  gateway:
    host: aqua-gateway
    port: 8443
  token: "token"