apiVersion: operator.aquasec.com/v1alpha1
kind: AquaScanner
metadata:
  name: aqua
spec:
  infra:                                    
    serviceAccount: "aqua-sa"               
    version: "4.5"                          
  deploy:                                   
    replicas: 1                             
  login:                                    
    username: "scanner"
    password: "Password1"
    host: "aqua-server"
