apiVersion: operator.aquasec.com/v1alpha1
kind: AquaServer
metadata:
  name: aquq
spec:
  infra:                                    # Optional: Infrastructure information
    serviceAccount: "aqua-sa"               # Optional: auto generate if requirment is true
    namespace: "aqua"                       # Optional: auto generate if requirment is true
    version: "4.6"                          # Optional: auto generate if requirment is true to latest version
    platform: "openshift"                   # Optional: auto generate if requirment is true to openshift
  common:
    clusterMode: false                      # Optional: if to work with cluster mode if you have more then 1 server, default false
    activeActive: false                     # Optional: if to work with cluster mode if you have more then 1 server, default false
    storageclass: "default"                 # Optional: if not given then use storage class default
    cybercenterAddress:                     # Optional: if not given then use default https://cybercenter.aquasec.com
    imagePullSecret:                        # Optional: if already created image pull secret then mention in here
    adminPassword:                          # Optional: if already created admin password secret
      key:
      name:
    license:                                # Optional: if already created license secret
      key:
      name:
    databaseSecret:                         # Optional: if already created database password secret
      key:
      name:
    serverDiskSize:                         # Optional: size of aqua server pvc if not given use default value 4
  externalDb:                               # Optional: if want to use external db and not internal database
    host:
    port:
    username:
    password:                               # Optional: if not using the common.databaseSecret
  deploy:                                   # Required: information about aqua server deployment
    replicas: 1                             # Required: number of replicas
    service: "LoadBalancer"                 # Required: service type for aqua server
    image:                                  # Optional: if not given take the default value and version from infra.version
      repository: "server"                  # Optional: if not given take the default value - server
      registry: "registry.aquasec.com"      # Optional: if not given take the default value - registry.aquasec.com
      tag: "4.6"                            # Optional: if not given take the default value - 4.5 (latest tested version for this operator version)
      pullPolicy: "IfNotPresent"            # Optional: if not given take the default value - IfNotPresent
  adminPassword:                            # Optional: Aqua Admin Password String
  licenseToken:                             # Optional: License Token String
