apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqua-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aqua-operator
  template:
    metadata:
      labels:
        name: aqua-operator
    spec:
      serviceAccountName: aqua-operator
      containers:
        - name: aqua-operator
          image: "aquasec/aqua-operator:1.0.0"
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - aqua-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "aqua-operator"
